use_frameworks!

platform :ios, '13.0'

target 'Rudder-CustomerIO_Example' do
  pod 'Rudder-CustomerIO', :path => '../'

  target 'Rudder-CustomerIO_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
